name: online_cv
description: An online version of my CV, built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  jovial_svg: ^1.1.29
  google_fonts: ^8.1.0
  phosphor_flutter: ^2.1.0
  super_sliver_list: ^0.4.1
  url_launcher: ^6.3.2
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: '#0284C7'
  image: 'assets/images/splash_image.png'
